show/urls.py
from django.conf.urls import url 
from . import views

app_name = 'show'

urlpatterns = [
	
	# index
	url(r'^$', views.IndexView.as_view(), name='index'),

	url(r'^about/$', views.AboutView.as_view(), name='about'),

	# form to add show
	url(r'^add/$', views.ShowCreate.as_view(), name='show-add'),

	# edit show
	#url(r'^(?P<show>[\w ]+)/edit/$', views.ShowUpdate.as_view(), name='show-update'),

	# delete show
	url(r'^(?P<show>[\w ]+)/delete/$', views.ShowDelete.as_view(), name='show-delete'),

	# signup
	url(r'^register/$', views.UserFormView.as_view(), name='register'),

	# login
	url(r'^login/$', views.LoginView.as_view(), name='login'),

	# logout
	url(r'^logout/$', views.LogoutView.as_view(), name='logout'),

	url(r'^error/$', views.ErrorView.as_view(), name='error'),

	url(r'^(?P<show>[\w ]+)/$', views.ShowDetail.as_view(), name='show-detail'),

	url(r'^(?P<show>[\w ]+)/addseason/$', views.AddSeason.as_view(), name='addseason'),

	url(r'^(?P<show>[\w ]+)/subtractseason/$', views.SubtractSeason.as_view(), name='subtractseason'),

	url(r'^(?P<show>[\w ]+)/addepisode/$', views.AddEpisode.as_view(), name='addepisode'),

	url(r'^(?P<show>[\w ]+)/subtractepisode/$', views.SubtractEpisode.as_view(), name='subtractepisode'),


]

tvsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('show.urls')),
]

show/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.core.validators import MinValueValidator

class Show(models.Model):
	owner = models.ForeignKey(User, null=True, default=True, related_name='o')
	title = models.CharField(max_length=100)
	description = models.TextField(default='N/A', blank=True, max_length=250)
	season = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])
	episode = models.PositiveIntegerField(default=0, validators=[MinValueValidator(0)])

	def get_absolute_url(self):
		return reverse('show:index')

	def __str__(self):
		return self.title

show/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ['username', 'password']

show/views.py
from django.shortcuts import render, redirect
from django.views import generic
from django.views.generic.detail import DetailView
from .models import Show
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View, TemplateView
from django.core.urlresolvers import reverse_lazy, reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User 
from .forms import UserForm
from django.shortcuts import get_object_or_404

class IndexView(generic.ListView):
	template_name = 'show/index.html'
	context_object_name = 'shows'

	def get_queryset(self):
		if self.request.user.is_authenticated():
			return Show.objects.filter(owner=self.request.user)
		else:
			return None

class AboutView(TemplateView):
	template_name = 'show/about.html'

class ShowDetail(DetailView):
	model = Show
	slug_field = "title"
	slug_url_kwarg = "show"
	template_name = 'show/show-detail.html'

	def get_queryset(self):
		return Show.objects.filter(owner=self.request.user)

class ShowCreate(CreateView):
	model = Show
	fields = ['title', 'description', 'season', 'episode']

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.owner = self.request.user
		instance.save()

		return redirect('show:index')
"""
class ShowUpdate(UpdateView):
	model = Show
	slug_field = 'title'
	slug_url_kwarg = 'show'
	fields = ['description', 'season', 'episode']
"""

class AddSeason(UpdateView):
	model = Show
	slug_field = 'title'
	slug_url_kwarg = 'show'
	fields = []

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.season += 1
		instance.save()

		return redirect('show:index')

class SubtractSeason(UpdateView):
	model = Show
	slug_field = 'title'
	slug_url_kwarg = 'show'
	fields = []

	def form_valid(self, form):
		instance = form.save(commit=False)
		if (instance.season > 0):
			instance.season -= 1
		else:
			instance.season = 0

		instance.save()

		return redirect('show:index')

class AddEpisode(UpdateView):
	model = Show
	slug_field = 'title'
	slug_url_kwarg = 'show'
	fields = []

	def form_valid(self, form):
		instance = form.save(commit=False)
		instance.episode += 1
		instance.save()

		return redirect('show:index')

class SubtractEpisode(UpdateView):
	model = Show
	slug_field = 'title'
	slug_url_kwarg = 'show'
	fields = []

	def form_valid(self, form):
		instance = form.save(commit=False)
		if (instance.episode > 0):
			instance.episode -= 1
		else:
			instance.episode = 0

		instance.save()

		return redirect('show:index')

class ShowDelete(DeleteView):
	model = Show
	slug_field = 'title'
	slug_url_kwarg = 'show'
	success_url = reverse_lazy('show:index')

class UserFormView(View):
	"""
	User sign up. Logs them in after sign up. (74)
	"""
	form_class = UserForm
	template_name = 'show/registration_form.html'

	def get(self, request):
		form = self.form_class(None)
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = self.form_class(request.POST)

		if form.is_valid():
			user = form.save(commit=False)

			username = form.cleaned_data['username']

			if not User.objects.filter(username=username).exists():
				password = form.cleaned_data['password']
				user.set_password(password)
				user.save()

				user = authenticate(username=username, password=password)

				if user is not None:

					if user.is_active:
						login(request, user)
						return redirect('show:index')
			else:
				return redirect('show:error')
		else:
			return redirect('show:error')


class LoginView(View):
	"""
	Log in already existing user
	"""
	form_class = UserForm
	template_name = 'show/registration_form.html'

	def get(self, request):
		form = self.form_class(None) 
		return render(request, self.template_name, {'form': form})

	def post(self, request):
		form = self.form_class(request.POST)

		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(username=username, password=password)

		if user is not None:

			if user.is_active:
				login(request, user)
				return redirect('show:index')
			else:
				return redirect('show:error')
		else:
			return redirect('show:error')

class LogoutView(View):

	def get(self, request):
		logout(request)
		return redirect('show:index')

class ErrorView(TemplateView):
	template_name = 'show/error.html'

show/templates/show/about.html
{% extends 'show/base.html' %}
{% block title %}About{% endblock %}

{% block content %}
<div class="row">
	<div class="col-xs-12">
		<h1 class="headertitle"><a href="{% url 'show:index' %}" class="linktitle">Watcher</a></h1>
	</div><!--col-->
</div><!--row-->

<div class="about">
	<div class="row">
		<div class="col-xs-12">
			<p class="lead text-center abouttext">
				Watcher is the app for binge watchers, weeaboos, soap opera enthusiasts, and procrastinators. Keep track of your episodes so you can watch without having to worry about forgetting what episode you're at.
			</p>
		</div><!--col-->
	</div><!--row-->
</div><!--about-->
{% endblock %}

show/templates/show/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Track{% endblock %}</title>
	<link rel="stylesheet" href="{% static 'show/bootstrap.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'show/styles.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'show/hover.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
	<link rel="icon" 
      type="image/png" 
      href="{% static 'show/img/white-book.png' %}">
</head>
<body>
<div class="container">
	{% block content %}
	{% endblock %}
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script>
<script type="text/javascript" src="{% static 'show/script.js' %}"></script>
</body>
</html>

show/templates/show/error.html
{% extends 'show/base.html' %}
{% block title %}Error{% endblock %}

{% block content %}
<h1>Something went wrong!</h1>
<a href="{% url 'show:index' %}" style="color: white;">Click me to go back</a>
{% endblock %}

show/templates/show/form-template.html
{% for field in form %}
<div class="form">
	<h3>{{field.label_tag}}</h3>
	<div class="field">{{field}}</div>
</div><!--form-->
{% endfor %}

show/templates/show/index.html
{% extends 'show/base.html' %}
{% block title %}Tracker{% endblock %}

{% block content %}
{% if user.is_authenticated %}

<div class="row">
	<div class="col-xs-12">
		<h1 class="headertitle"><a href="{% url 'show:index' %}" class="linktitle">Watcher</a></h1>
	</div><!--col-->
</div><!--row-->

<div class="menu">
	<div class="row">
		<div class="col-xs-12 col-sm-4">
			<a href="{% url 'show:show-add' %}" class="cbtn index-btn hvr-glow">Add show</a>
			<a href="{% url 'show:logout' %}" class="cbtn index-btn hvr-glow">Log out</a>
		</div><!--col-->
	</div><!--row-->
</div><!--menu-->

<div class="row">
	<div class="col-md-offset-1 col-xs-12 col-sm-11">
		<div class="shows">
			<div class="row">
				{% for show in shows %}
				<div class='col-xs-12 col-sm-5 show'>
					<h2 class="show-title"><a class="title-link" href="{% url 'show:show-detail' show=show %}">{{show.title}}</a></h2>
					<div class="show-season show-form">
					<p class="show-info">Season: {{show.season}}</p>
					<form action="{% url 'show:addseason' show=show %}" method="post" class="change">
						{% csrf_token %}

						<button class="btn btn-default" type="submit">+</button>
					</form>	

					<form action="{% url 'show:subtractseason' show=show %}" method="post" class="change">
						{% csrf_token %}

						<button class="btn btn-default" type="submit">-</button>
					</form>
				</div>

			<div class="show-episode show-form">
				<p class="show-info">
					Episode: {{show.episode}}   
				</p>
				<form action="{% url 'show:addepisode' show=show %}" method="post" class="change">
					{% csrf_token %}

					<button class="btn btn-default" type="submit">+</button>
				</form>	

				<form action="{% url 'show:subtractepisode' show=show %}" method="post" class="change">
					{% csrf_token %}

					<button class="btn btn-default" type="submit">-</button>
				</form>	

			</div>
					<div class="show-description">
						<h3 class="description-text">
							{% ifnotequal show.description 'N/A' %}
							Description: {{show.description}}
							{% endifnotequal %}
						</h3>
					</div>
				</div><!--show-->
				{% endfor %}
			</div><!--row-->
		</div><!--shows-->
	</div><!--col-->
</div>

{% else %}
<div class="row">
	<div class="col-xs-12">
		<div class="landing">
			<h1 id="apptitle">Watcher</h1>
			<p class="text-center slogan">Keep track of your episodes.</p>
		</div><!--landing-->
	</div><!--col-->
</div><!--row-->
<div class="row">
	<div class="col-xs-12 sign text-center">
		<a href="{% url 'show:about' %}" class="cbtn user-btn hvr-glow">About</a>
		<a href="{% url 'show:register' %}" class="cbtn user-btn hvr-glow">Sign up</a>
		<a href="{% url 'show:login' %}" class="cbtn user-btn hvr-glow">Log in</a>
	</div><!--sign-->
</div><!--row-->
{% endif %}

{% endblock %}

show/templates/show/registration_form.html
{% extends 'show/base.html' %}
{% block title %}Register/Log in {% endblock %}

{% block content %}

{% if not user.is_authenticated %}
<div class="row">
	<div class="col-md-offset-3 col-xs-12 col-sm-5 user-form">
		<h1 class="user-title">Watcher</h1>
		<div class="form-group">
			<form action="" method="post">
			{% csrf_token %}

			{% include 'show/form-template.html' %}
			<br>
			<button class="btn btn-secondary btn-lg" type="submit">Submit</button>

			</form>

		</div><!--form-group-->
	</div><!--col-->
</div><!--row-->
{% else %}
<h1>You are already logged in!</h1>
{% endif %}

{% endblock %}

show/templates/show/show-detail.html
{% extends 'show/base.html' %}
{% block title %}Detail{% endblock%}

{% block content %}
<div class="row">
	<div class="col-xs-12">
		<h1 class="headertitle"><a href="{% url 'show:index' %}" class="linktitle">Watcher</a></h1>
	</div><!--col-->
</div><!--row-->

<div class="row">
	<div class="col-md-offset-1 col-xs-12 col-sm-10 text-center">
		<div class="show-detail">
			<h1 class="show-title">{{show}}</h1>

			<h3 class="description-text">Description: {{show.description}}</h3>
				<div class="show-season show-form">
				<p class="show-info">Season: {{show.season}}</p>
				</div>

				<div class="show-episode show-form">
					<p class="show-info">
					Episode: {{show.episode}}
					</p>
				</div>

				<div class="detail-form show-form">

					<form action="{% url 'show:show-delete' show=show %}" method="post">
					{% csrf_token %}
					<button class="btn btn-secondary btn-lg" type="submit">Delete</button>
					</form>
				</div><!--btn group-->
				
		</div><!--show-detail-->
	</div><!--col-->
</div><!--row-->
{% endblock %}

show/templates/show/show_form.html
{% extends 'show/base.html' %}
{% block title %}Add Show{% endblock %}

{% block content %}
<h1 class="user-title">Watcher</h1>

{% if user.is_authenticated %}
<div class="row">
	<div class="col-md-offset-3 col-xs-12 col-sm-6 user-form">
		<div class="form-group">
			<form action="" method="post">
			{% csrf_token %}
			<h1>Add show</h1>
			{% include 'show/form-template.html' %}
			<br>
			<button class="btn btn-secondary btn-lg" type="submit">Submit</button>
			</form>
		</div><!--form-group-->
	</div><!--col-->
</div><!--row-->
{% else %}
<a href="{% url 'show:register' %}">Sign up</a>
<a href="{% url 'show:login' %}">Log in</a>
{% endif %}
{% endblock %}